server:
  port: 8888

spring:
  application:
    name: sinsahelper-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/woozxn/sinsahelper_config
          username: woozxn
          password: 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