server:
  port: 8888

spring:
  application:
    name: sinsahelper-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/woozxn/sinsahelper_config.git
          username: woozxn
          password: secret